import("//third_party/closure_compiler/compile_js.gni")
import("//tools/polymer/html_to_js.gni")
import("../os_settings.gni")

polymer_element_files = [
  "fydeos_account.js",
  "fydeos_drivers.js",
  "fydeos_more_info.js",
  "fydeos_remoting.js",
  "fydeos_tweak_ui.js",
  "fydeos_experiment.js",
  "os_fyde_page.js",
]

js_type_check("closure_compile_module") {
  closure_flags = os_settings_closure_flags
  is_polymer3 = true
  deps = [
    ":shell_client",
    ":fydeos_account",
    ":fydeos_drivers",
    ":fydeos_remoting",
    ":fydeos_more_info",
    ":fydeos_tweak_ui",
    ":fydeos_experiment",
    ":os_fyde_page",
  ]
}

js_library("shell_client") {
  deps = [
    "//ui/webui/resources/js:cr.m"
  ]
}

js_library("fydeos_account") {
  deps = [
    "//third_party/polymer/v3_0/components-chromium/polymer:polymer_bundled",
    "//ui/webui/resources/js:i18n_behavior.m",
    "//ui/webui/resources/js:cr.m",
    "../os_people_page:account_manager_browser_proxy",
    "//ui/webui/resources/js:load_time_data.m",
    "//ui/webui/resources/js:web_ui_listener_behavior.m",
    "//ui/webui/resources/cr_elements/chromeos/cr_picture:png",
    "//ui/webui/resources/js:icon",
  ]
}

js_library("fydeos_drivers") {
  deps = [
    "..:os_route",
    "../..:router",
    "..:route_observer_behavior",
    ":shell_client",
    "//third_party/polymer/v3_0/components-chromium/polymer:polymer_bundled",
    "//ui/webui/resources/js:i18n_behavior.m",
     "//ui/webui/resources/js:web_ui_listener_behavior.m",
  ]
}

js_library("fydeos_remoting") {
  deps = [
    "//third_party/polymer/v3_0/components-chromium/polymer:polymer_bundled",
    "//ui/webui/resources/js:i18n_behavior.m",
    "..:os_route",
    "../..:router",
    ":shell_client",
  ]
}

js_library("fydeos_more_info") {
  deps = [
    "../os_about_page:about_page_browser_proxy",
    "//third_party/polymer/v3_0/components-chromium/polymer:polymer_bundled",
  ]
}

js_library("fydeos_tweak_ui") {
  deps = [
    "..:route_observer_behavior",
     "//ui/webui/resources/js:cr.m",
     "//ui/webui/resources/js:load_time_data.m",
     "//ui/webui/resources/js:i18n_behavior.m",
     "//ui/webui/resources/js:web_ui_listener_behavior.m",
    "//third_party/polymer/v3_0/components-chromium/polymer:polymer_bundled",
    ":shell_client",
  ]
}

js_library("fydeos_experiment") {
  deps = [
    "//ui/webui/resources/js:cr.m",
    "//ui/webui/resources/js:load_time_data.m",
    "../..:lifetime_browser_proxy",
    "//third_party/polymer/v3_0/components-chromium/polymer:polymer_bundled",
  ]
}

js_library("os_fyde_page") {
  deps = [
    "//ash/webui/common/resources:i18n_behavior",
    "..:route_observer_behavior",
  ]
}

html_to_js("web_components") {
  js_files = polymer_element_files
}
