# Copyright 2018 The FydeOS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//build/config/chromeos/rules.gni")

assert(is_chromeos, "Non-Chrome-OS builds must not depend on //chromeos")

source_set("switches") {
  public_deps = []
  deps = [
    "//base",
  ]
  sources = [
    "display/display_switches.cc",
    "display/display_switches.h",

    "urls/urls_constants.cc",
    "urls/urls_constants.h",

    "account/account_switches.cc",
    "account/account_switches.h",
    "account/account_constants.cc",
    "account/account_constants.h",
    "account/policy_constants.cc",
    "account/policy_constants.h",

    "misc/misc_switches.cc",
    "misc/misc_switches.h",
    "misc/misc_constants.cc",
    "misc/misc_constants.h",

    "services/services_switches.cc",
    "services/services_switches.h",
    "services/services_constants.cc",
    "services/services_constants.h",
  ]
  defines = [ "CHROMEOS_IMPLEMENTATION" ]
}
